//! REGISTER TYPES
export const REGISTER_PENDING = 'REGISTER_PENDING';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';

//! LOGIN TYPES
export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

//! LOAD USER TYPES
export const LOAD_USER_PENDING = 'LOAD_USER_PENDING';
export const LOAD_USER_FAIL = 'LOAD_USER_FAIL';
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';

//! LOGOUT TYPES
export const LOGOUT_PENDING = 'LOGOUT_PENDING';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';