//! CREATE CART TYPES
export const CREATE_CART_PENDING = 'CREATE_CART_PENDING';
export const CREATE_CART_FAIL = 'CREATE_CART_FAIL';
export const CREATE_CART_SUCCESS = 'CREATE_CART_SUCCESS';

//! FETCH ITEMS TYPES
export const FETCH_ALL_PENDING = 'FETCH_ALL_PENDING';
export const FETCH_ALL_FAIL = 'FETCH_ALL_PENDING';
export const FETCH_ALL_SUCCESS = 'FETCH_ALL_SUCCESS';

//! MARK COMPLETE TYPES
export const MARK_COMPLETE_PENDING = 'MARK_COMPLETE_PENDING';
export const MARK_COMPLETE_FAIL = 'MARK_COMPLETE_FAIL';
export const MARK_COMPLETE_SUCCESS = 'MARK_COMPLETE_SUCCESS';

//! MARK UN-COMPLETE TYPES
export const MARK_UNCOMPLETE_PENDING = 'MARK_UNCOMPLETE_PENDING';
export const MARK_UNCOMPLETE_FAIL = 'MARK_UNCOMPLETE_FAIL';
export const MARK_UNCOMPLETE_SUCCESS = 'MARK_UNCOMPLETE_SUCCESS';

//! DELETE TYPES
export const DELETE_PENDING = 'DELETE_PENDING';
export const DELETE_FAIL = 'DELETE_FAIL';
export const DELETE_SUCCESS = 'DELETE_SUCCESS';