//! CREATE DAY TYPES
export const CREATE_DAY_PENDING = 'CREATE_DAY_PENDING';
export const CREATE_DAY_FAIL = 'CREATE_DAY_FAIL';
export const CREATE_DAY_SUCCESS = 'CREATE_DAY_SUCCESS';

//! DELETE DAY TYPES
export const DELETE_DAY_PENDING = 'DELETE_DAY_PENDING';
export const DELETE_DAY_FAIL = 'DELETE_DAY_FAIL';
export const DELETE_DAY_SUCCESS = 'DELETE_DAY_SUCCESS';

//! FETCH ALL DAYS TYPES
export const FETCH_DAYS_PENDING = 'FETCH_DAYS_PENDING';
export const FETCH_DAYS_FAIL = 'FETCH_DAYS_FAIL';
export const FETCH_DAYS_SUCCESS = 'FETCH_DAYS_SUCCESS';

//! SET DAY TYPES
export const SET_DAY_PENDING = 'SET_DAY_PENDING';
export const SET_DAY_FAIL = 'SET_DAY_FAIL';
export const SET_DAY_SUCCESS = 'SET_DAY_SUCCESS';
